// app/products.js
export const products = [
    {
        id: 1,
        name: 'Grow Circles T-Shirt',
        price: '₹20.00',
        images: ['/tshirt.png', '/tshirt.png'],
        description: 'A comfortable T-shirt with a unique circles design.',
    },
    {
        id: 2,
        name: 'Grow String Bag',
        price: '₹12.00',
        images: ['/hoodie-1 (3).png'],
        description: 'A stylish String bag perfect for daily use.',
    },
    {
        id: 3,
        name: 'Grow Mug',
        price: '₹15.00',
        images: ['cup-white (2).png'],
        description: 'A sturdy cup with the Grow logo.',
    },
    {
        id: 4,
        name: 'Grow Hat',
        price: '₹10.00',
        images: ['/hat-1 (2).png'],
        description: 'A cool hat to keep the sun away.',
    },
    {
        id: 5,
        name: 'Grow Hoodie',
        price: '₹25.00',
        images: ['/hoodie-1 (3).png'],
        description: 'Comfortable and stylish hoodies.',
    },
    {
        id: 3,
        name: 'Grow Mug',
        price: '₹15.00',
        images: ['cup-white (2).png'],
        description: 'A sturdy cup with the Grow logo.',
    },
    {
        id: 4,
        name: 'Grow Hat',
        price: '₹10.00',
        images: ['/hat-1 (2).png'],
        description: 'A cool hat to keep the sun away.',
    },
    {
        id: 5,
        name: 'Grow Hoodie',
        price: '₹25.00',
        images: ['/hoodie-1 (3).png'],
        description: 'Comfortable and stylish hoodies.',
    },
    {
        id: 3,
        name: 'Grow Mug',
        price: '₹15.00',
        images: ['cup-white (2).png'],
        description: 'A sturdy cup with the Grow logo.',
    },
    {
        id: 4,
        name: 'Grow Hat',
        price: '₹10.00',
        images: ['/hat-1 (2).png'],
        description: 'A cool hat to keep the sun away.',
    },
    {
        id: 5,
        name: 'Grow Hoodie',
        price: '₹25.00',
        images: ['/hoodie-1 (3).png'],
        description: 'Comfortable and stylish hoodies.',
    }
];
